apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: payoneer
    repoURL: git@bitbucket.org:metascan/metadefender-k8s.git
    targetRevision: MDK8S-237-argocd
    directory:
      recurse: true
      include: payoneer
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: false
      prune: true